In [ ]:
# Categorical, Dummy variables, One-hot encoding
# -->pandas  get_dummies
# --> sklearn OneHotEncoding

In [ ]:
# category - nominal -male/female
# category -ordinal - ratings/ranks

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.DataFrame({
    'area':[2600,3000,3200,3600,4000],
    'price':[550000, 570000,600000, 650000, 700000],
    'bedroom':[3,4,None,3,5],
    'age':[20,15,18,30,5]
})
df

,area,price,bedroom,age
0,2600,550000,3.0,20
1,3000,570000,4.0,15
2,3200,600000,NaN,18
3,3600,650000,3.0,30
4,4000,700000,5.0,5


In [4]:
df.to_csv('homeprice.csv')

In [5]:
df=pd.read_csv('homeprice.csv')
df

,town,area,price
0,monroe township,2600,550000
1,monroe township,3000,570000
2,monroe township,3200,600000
3,monroe township,3600,650000
4,monroe township,4000,700000
5,west windsor,3900,780000
6,west windsor,3400,650000
7,west windsor,2300,500000
8,west windsor,5000,800000
9,robinsville,4500,750000


In [6]:
dumm = pd.get_dummies(df.town)

In [7]:
dumm

,monroe township,robinsville,west windsor
0,1,0,0
1,1,0,0
2,1,0,0
3,1,0,0
4,1,0,0
5,0,0,1
6,0,0,1
7,0,0,1
8,0,0,1
9,0,1,0


In [10]:
merged = pd.concat([df, dumm], axis='columns')

In [9]:
merged

,town,area,price,monroe township,robinsville,west windsor
0,monroe township,2600,550000,1,0,0
1,monroe township,3000,570000,1,0,0
2,monroe township,3200,600000,1,0,0
3,monroe township,3600,650000,1,0,0
4,monroe township,4000,700000,1,0,0
5,west windsor,3900,780000,0,0,1
6,west windsor,3400,650000,0,0,1
7,west windsor,2300,500000,0,0,1
8,west windsor,5000,800000,0,0,1
9,robinsville,4500,750000,0,1,0


In [13]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/9yl6-HEY7_s?si=UKKa3-zsrte27G4x" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

In [11]:
final = merged.drop(columns=['town', 'west windsor'], axis=1) #drop one town columns to avoid multicolinearity

In [12]:
final

,area,price,monroe township,robinsville
0,2600,550000,1,0
1,3000,570000,1,0
2,3200,600000,1,0
3,3600,650000,1,0
4,4000,700000,1,0
5,3900,780000,0,0
6,3400,650000,0,0
7,2300,500000,0,0
8,5000,800000,0,0
9,4500,750000,0,1


In [14]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()


In [15]:
X=final.drop('price',axis=1)

In [16]:
y=final.price

In [18]:
model.fit(X,y)

LinearRegression()

In [20]:
# robinsville home
model.predict([[2800,0,1]])

C:\Users\pc\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([545042.52303331])

In [21]:
# monroe township home
model.predict([[2800,1,0]])

C:\Users\pc\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([571630.04961021])

In [22]:
# west windsor home
model.predict([[2800,0,0]])

C:\Users\pc\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([607469.87951807])

In [23]:
model.score(X,y)

0.6996962558908828

In [24]:
# One hot encoding - label encoder
from sklearn.preprocessing import LabelEncoder

In [26]:
df = pd.read_csv('homeprice.csv')
df

,town,area,price
0,monroe township,2600,550000
1,monroe township,3000,570000
2,monroe township,3200,600000
3,monroe township,3600,650000
4,monroe township,4000,700000
5,west windsor,3900,780000
6,west windsor,3400,650000
7,west windsor,2300,500000
8,west windsor,5000,800000
9,robinsville,4500,750000


In [27]:
le = LabelEncoder()
le_town = le.fit_transform(df.town)
le_town

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1])

In [28]:
df1=df

In [29]:
df1.town =le_town

In [30]:
df1

,town,area,price
0,0,2600,550000
1,0,3000,570000
2,0,3200,600000
3,0,3600,650000
4,0,4000,700000
5,2,3900,780000
6,2,3400,650000
7,2,2300,500000
8,2,5000,800000
9,1,4500,750000


In [72]:
X=df1[['town','area']].values
y =df1.price

In [59]:
X,y

(array([[   0, 2600],
        [   0, 3000],
        [   0, 3200],
        [   0, 3600],
        [   0, 4000],
        [   2, 3900],
        [   2, 3400],
        [   2, 2300],
        [   2, 5000],
        [   1, 4500],
        [   1, 3400],
        [   1, 5200]], dtype=int64),
 0     550000
 1     570000
 2     600000
 3     650000
 4     700000
 5     780000
 6     650000
 7     500000
 8     800000
 9     750000
 10    650000
 11    650000
 Name: price, dtype: int64)

In [73]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [79]:
encoded = ohe.fit_transform(X[:,[0]])
encoded

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [80]:
import numpy as np
area_col = X[:,[1]]
X=np.hstack((encoded,area_col))
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 3.9e+03],
       [0.0e+00, 1.0e+00, 3.4e+03],
       [0.0e+00, 1.0e+00, 2.3e+03],
       [0.0e+00, 1.0e+00, 5.0e+03],
       [1.0e+00, 0.0e+00, 4.5e+03],
       [1.0e+00, 0.0e+00, 3.4e+03],
       [1.0e+00, 0.0e+00, 5.2e+03]])

In [82]:
X=X[:,1:]

In [84]:
model.fit(X,y)

LinearRegression()

In [85]:
model.score(X,y)

0.689041115976872

In [88]:
model.predict([[0,2600]])

array([550701.09390538])

In [ ]:
# Train Test validation model
# when we split the data, it chooses random data each time to avoid this we use 
# random_state helps to use the same data points

In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=56)