In [1]:
import numpy as np

y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.7, 0.30,1,0,0.5])

In [9]:
# without using numpy 

def mae(y_true, y_pred):
    total_error =0
    for yt,yp in zip(y_true, y_pred):
        total_error += abs(yt-yp)
    mae = total_error/len(y_true)
    return mae

In [11]:
mae = mae(y_true, y_pred)

In [13]:
print('Mean absolute error: ', mae)

Mean absolute error:  0.5


In [14]:
# with numpy

(y_pred- y_true)

array([ 0.3,  0.7, -1. ,  0. ,  0.5])

In [16]:
np.abs(y_pred- y_true)

array([0.3, 0.7, 1. , 0. , 0.5])

In [17]:
np.mean(np.abs(y_pred- y_true))

0.5

In [18]:
# mean squared error - without numpy

def mse(y_true, y_pred):
    total_error = 0
    for yt, yp in zip(y_true, y_pred):
        total_error += (yt-yp)**2
    mse = total_error/len(y_true)
    print('Total error: ', total_error)
    print("Mean squared error : ", mse)

In [19]:
mse(y_true, y_pred)

Total error:  1.83
Mean squared error :  0.366


In [20]:
# with numpy

(y_pred - y_true)**2

array([0.09, 0.49, 1.  , 0.  , 0.25])

In [22]:
np.square(y_pred - y_true)

array([0.09, 0.49, 1.  , 0.  , 0.25])

In [25]:
np.sum(np.square(y_pred - y_true))

1.83

In [23]:
np.mean(np.square(y_pred - y_true))

0.366

In [26]:
#  for log function we need to take value clost to zero but not zero

# for example

np.log(0)      #will give undefined value so need to replace 0 to different values

C:\Users\pc\AppData\Local\Temp\ipykernel_5488\2497729573.py:5: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [27]:
np.log([0.0000000000002])

array([-29.24045903])

In [31]:
epsilon = 1e+15
print(epsilon)

epsilon = 1e-15
print(epsilon)

1000000000000000.0
1e-15


In [32]:
y_pred

array([1, 1, 0, 0, 1])

In [36]:
y_pred_new = [max(i, epsilon) for i in y_pred ]
y_pred_new                  #it replaces 0 to close to 0

[1, 1, 1e-15, 1e-15, 1]

In [37]:
y_pred_new = [min(i,1- epsilon) for i in y_pred_new ]
y_pred_new 

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [38]:
y_pred_new = np.array(y_pred_new)
y_pred_new               #list to numpy array to remove infinite value

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [39]:
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [40]:
np.log(y_pred)

C:\Users\pc\AppData\Local\Temp\ipykernel_5488\4184140517.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_pred)


array([  0.,   0., -inf, -inf,   0.])

In [41]:
# log loss

-np.mean(y_true*np.log(y_pred_new) +(1-y_true)*np.log(1-y_pred_new))

17.2696280766844

In [44]:
def log_loss(y_true, y_pred):
    epsilon = 1e-15
    y_pred_new = [max(i, epsilon) for i in y_pred]
    y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    ll = -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))
    return ll

In [45]:
log_loss(y_true, y_pred)

17.2696280766844